pluto: add new sa_expire_kind to track specific expiry event on state
This is so that a hard expire event doesn't go and trigge calls to
get_sa_info() for traffic counters or del_spi() to build the netlink
messages to talk to a SPI the kernel no longers knows anything about.

This was causing littering of:

	ERROR: netlink response for Get SA esp.35c35571@192.1.2.23 included errno 3: No such process

and

	ERROR: netlink response for Del SA esp.d502272f@192.1.2.23 included errno 3: No such process